# Name of the Github Workflow
name: "Github Workflow Name"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job_01:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Custom Steps
      - name: Run a one-line script
        run: echo Hello, world!

      # Custom Steps
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo test > file.txt
  job_02:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Custom Steps
      - name: Run a one-line script
        run: echo Hello, world!
      
      # Custom Steps
      - name: Custom Command
        run: pwd ; ls -ltra ; dir